날씨앱 [STEP 1] jacob
yagom-academy/refactoring-weather pull request #10
Opened 2024-02-03 09:55 UTC by wargi

안녕하세요 @zdodev !

### 고민했던 점
`ViewController`의 네이밍을 `WeatherListViewController`로 수정했습니다.
`VC`에 꼭 `View`로 분리해야하는 생각이 들어서, `ViewModel`을 하나만들어서 분리하였습니다.
날씨 데이터를 불러오는 로직을 프로토콜과 실존 타입으로 분리해보았습니다.
`WeatherJson`으로 불러오는 `DTO`를 `Mapping`해서 `Entity`로 만들어보았습니다!

### 해결하지 못한 부분
`TempUnit`의 의존성을 모델이 가지고 있는데 이를 어떻게 풀어나가야할지 고민됩니다.
현재 모델, `Service`모두 `TempUnit`을 의존하고 있어서 어떻게 생각하시는지 궁금합니다!

### 조언을 얻고 싶은 부분
`WeatherDetailViewController`같은 경우에는 `ViewModel`을 따로 만들진 않았는데요..
이렇게 생각한 이유는 너무 간단하게 **configure data**만 하고 있어서 `ViewModel`을 만들기에 투머치하다는 생각을 했는데요.
하지만 모델의 의존성은 가지고 있는듯한데, 모델의 의존성은 그대로 두어도 되는지 소대라면 어떻게 하셨을지 궁금합니다!

소대 너무 늦게 PR을 전달드려 죄송합니다🥲

2024-02-05 15:06 UTC, zdodev requested changes
안녕하세요. @wargi !

Step1 진행 잘해주셨습니다.👍
모델 분리와 원시값을 잘 포장해보셨네요!
`View`를 분리하기 위해, `ViewModel`을 만드신 점도 좋았습니다!

질문의 대한 생각과 함께 코멘트를 남겨보았습니다.
같이 의견 나눠보면 좋을 것 같습니다!😁

2024-02-05 15:06 UTC, zdodev commented on WeatherForecast/WeatherForecast/Scenes/List/Service/WeatherService.swift
> +}
SOLID 원칙을 지키기 위해 `WeatherService` 프로토콜을 정의해보셨네요.👍
`TempUnit`을 의존하고 있는 부분에 대한 질문에 대해서,
`WeatherService` 타입이 `TempUnit`을 알아야 할 이유가 있을까요?
의도하신 `WeatherService` 역할이 궁금합니다!

2024-02-05 15:06 UTC, zdodev commented on WeatherForecast/WeatherForecast/Scenes/List/WeatherListViewController.swift
> +        bind()
좋습니다.👍

2024-02-05 15:06 UTC, zdodev commented on WeatherForecast/WeatherForecast/Scenes/List/WeatherListViewModel.swift
> +}
Input, Output, Data 로직을 분리해보셨네요.👍

2024-02-05 15:06 UTC, zdodev commented on WeatherForecast/WeatherForecast/Scenes/Detail/WeatherDetailViewController.swift
> +        setWeatherForecastData()
메서드 역할을 잘 분리하여 정의해보셨네요.👍

2024-02-05 15:06 UTC, zdodev commented on WeatherForecast/WeatherForecast/Extensions/UIImage+.swift
> +    func loadImage(with urlString: String) {
`Utility`성 기능을 잘 분리해보셨네요!
UIImageView의 `extension`으로 구현하신 이유가 궁금합니다!

2024-02-05 15:06 UTC, zdodev commented on WeatherForecast/WeatherForecast/AppDelegate/SceneDelegate.swift
> +        let listVC: WeatherListViewController = WeatherListViewController(viewModel: weatherViewModel)
`DIP` 원칙을 잘 지켜보셨네요👍

2024-02-06 11:42 UTC, wargi commented on WeatherForecast/WeatherForecast/Extensions/UIImage+.swift
> +    func loadImage(with urlString: String) {
`ImageDownloadManager`처럼 싱글톤으로 매니저를 하나 만들어서 사용하는 방법과 현재 방법사이에서 고민해보았는데요!
간단한 다운로드 코드에 비해 오히려 복잡할까싶은 생각이들어서
`UIImageView`의 `extension`으로 처리하였습니다!

2024-02-06 12:01 UTC, wargi commented on WeatherForecast/WeatherForecast/Scenes/List/Service/WeatherService.swift
> +}
데이터를 받을 때, display되는 값도 같이 처리하고 싶은 생각으로 고민해보았는데🤔
이렇게 작성해보니 `Service`는 단순 데이터 요청하는 역할인데 `presenter`에서 해야하는 역할까지 같이하고 있었군여!
말씀주신 내용을 보고 고민해보고 [620cda2](https://github.com/yagom-academy/refactoring-weather/pull/10/commits/620cda20228161d695ce37dde90f0c14df44a3b8) 수정해보았습니다 :)

2024-02-07 15:34 UTC, zdodev approved these changes
안녕하세요. @wargi !

Step1 개선도 잘 진행해주셨네요!
`Service`로 분리한 타입에 대한 역할을 한번 더 확인해볼 수 있었지 않았나 싶습니다.
질문에 대한 코멘트를 추가로 달아보았습니다.
확인하고 넘어가면 좋을 것 같습니다. 고생하셨습니다🎉

2024-02-07 15:34 UTC, zdodev commented on WeatherForecast/WeatherForecast/Scenes/Detail/WeatherDetailViewController.swift
> +    private var tempUnit: TempUnit
말씀해주신 것 처럼 `configure data`만 하고 있는 부분과, 
역할 분리의 `ViewModel`이 아닌 `MVVM`을 위한 `ViewModel` 이 될꺼 같아서 지금과 같은 구현도 좋은 방법이 될 것 같습니다!
모델의 의존성을 가지고 있지만 지금과 같이 작은 엔티티를 유지한다면 허용할 수 있지 않을까 싶습니다!

2024-02-07 15:34 UTC, zdodev commented on WeatherForecast/WeatherForecast/Scenes/List/Service/WeatherService.swift
> +}
`tempUnit`를 사용하지 않도록 수정되어서 매개변수도 수정하면 좋을 것 같습니다.👍

2024-02-07 15:34 UTC, merged