날씨앱 [STEP 1] tonylim
yagom-academy/refactoring-weather pull request #13
Opened 2024-02-04 22:57 UTC by witlim1225

@havilog 3주차인데 이제야 2주차를 시작했네요.

# 고민했던 점
1. 스토리보드를 가져가는 최대한 가져가보면서 어디서 DI가 힘든지 고민을 좀 해봤습니다.
2. VC에서 View를 분리하는데, 해당 View에서 tableView를 쓰다보니 delegate설정을 어떻게 연결해줘야 할지 많이 고민했습니다.
3. 되도록 구체타입을 쓰지않으려고 노력했지만, 데이터가 들어가는 부분에 있어서는 어떻게 추상화 해볼 수 있을지 고민해봤습니다.

# 해결하지 못한 부분
WeatherTableViewCell과 WeatherDetailInfo에서 사용하는 model이 비슷한데, 1개씩만 달라서 이걸 각각의 목적에 맞게 따로 model을 만들어서 전달해야하는지, 아니면 optional기능으로 만들어서 필요한것만 넣어서 전달할 지 잘 모르겠습니다.

# 조언을 얻고 싶은 부분
시간과 노력이 많이 필요한 부분인 건 아는 부분인데, 살짝 넋두리를 해봅니다.
SOLID, 객체 미용 원칙을 공부하고 아 저렇게 하는거구나 하며, 코드를 수정합니다.
다만, 이게 내가 의도한 바를 제대로 바꾼 것인지, 1가지를 지키려다보니 다른걸 어기고 있지는 않은지와 같은 의문이 계속해서 듭니다. 이것에 대한 명확한 답은 어떤식으로 찾으시는 지 궁금합니다.

2024-02-05 14:36 UTC, havilog requested changes
> 이것에 대한 명확한 답은 어떤식으로 찾으시는 지 궁금합니다.

정답은 없다고 생각해요!
계속 짜보고 이렇게 짜면 이게 문제네 파악해보고
다른 사람의 코드를 보고 하면서 시간에 따라 성장하는 거 같습니다 ㅎㅎ

> WeatherTableViewCell과 WeatherDetailInfo에서 사용하는 model이 비슷한데, 1개씩만 달라서 이걸 각각의 목적에 맞게 따로 model을 만들어서 전달해야하는지, 아니면 optional기능으로 만들어서 필요한것만 넣어서 전달할 지 잘 모르겠습니다.

각각의 모델을 만들기보다는 두번 째 방식이 맞지 않을까 싶습니다!

나머지 부분은 코멘트 참고하여 수정하시구 알려주세요!

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/DetailDateFormattable.swift
> +}
```suggestion
protocol DateFormattable: AnyObject {
    func format(date: Date, with dateFormatter: DateFormatter) -> String
}
```

이런 느낌으로 프로토콜을 선언해보는건 어떨까요?

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +    private let iconImageView: UIImageView = UIImageView()
```suggestion
    private let iconImageView: UIImageView = .init()
```
요건 취향인데 요렇게 쓰면 코드량이 조금 줄어여 ㅎㅎ

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDataManager.swift
> +class WeatherDataManager: WeatherDataManagerDelegate {
상속하지 않는다면 final을 붙여주세요 ㅎㅎ

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDataManager.swift
> +    }
decoder 도 파라미터로 주입받을 수 있을거 같고, result에 반환할 값도 제네릭으로 선언할 수 있을거 같아요!

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailViewController.swift
> +    private let weatherDetailInfo: WeatherDetailInfo?
이 값은 반드시 optional이어야할까요?

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailViewController.swift
> +        guard let listInfo = weatherDetailInfo?.weatherForecastInfo else { return }
여기서 return이 된다면 weatherDetailInfo가 nil일 때 유저는 빈 화면을 보게 될 거 같아요!

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +        }
여기있는 데이트포매터도 분리해줄 수 있지 않을까요?

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +            }
Task와 DispatchQueue는 같이 쓰면 안되는 것으로 알고있어요!
Task에서 메인쓰레드로 돌아가게하려면 어떻게 해야할까요?

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +    }
URLSession을 직접선언하지 않고, 네트워크 담당 객체를 만들어서 그 객체가 수행하게하고 주입받으면 어떨까요?

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherTableViewCell.swift
> +    }
이미지 캐시를 담당하는 객체를 만들어서 해당 객체에 역할을 위임해보면 어떨까요?

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherTableViewCell.swift
> +    }
이 네트워크 객체도 위와 마찬가지로 분리할 수 있을거 같아요

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherView.swift
> +    let refreshControl: UIRefreshControl = UIRefreshControl()
이 아이들은 외부에서 접근해야하는 아이들인가요?

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherViewController.swift
> +        })
```suggestion
        dataManagerDelegate?.fetchWeatherData { [weak self] result in
            DispatchQueue.main.async {
                switch result {
                case .success(let info):
                    self?.weatherJSON = info
                    self?.updateUI()
                case .failure(let error):
                    print(error.localizedDescription)
                }
            }
        }
```

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherViewController.swift
> +            weatherForecastInfo: weatherJSON?.weatherForecast[indexPath.row],
weatherForecast[safe: indexPath.row]
이렇게 안전하게 subscript를 만들어 접근해보는건 어떨까요?

2024-02-05 14:36 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherViewController.swift
> +    }
weatherDetailInfo를 optional하게 받아오는 이유가 있을까요?

2024-02-05 15:00 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/DetailDateFormattable.swift
> +}
따로 함수를 어떻게 지정해줄지 고민하다가 extension을 사용했었는데 저렇게 하면 상황에 맞게 코드를 구현하기 좋겠네요.

2024-02-05 15:01 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +    private let iconImageView: UIImageView = UIImageView()
안그래도 회사에서 리팩토링하면서 느꼈는데, 코드량이 많아져서 나중엔 .init으로 만들고 있더라구요. 감사합니다 ㅎㅎ

2024-02-05 15:01 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDataManager.swift
> +    }
넵 한번 해보겠습니다.

2024-02-05 15:02 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDetailViewController.swift
> +    private let weatherDetailInfo: WeatherDetailInfo?
의존성을 주입받는다면, 굳이 optional일 필요는 없을 거 같습니다.
안전하게 처리한다고 습관적으로 optional을 쓴거 같아요.

2024-02-05 15:03 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +        }
안그래도 여기 보면서 많이 고민했었는데 위에서 주신 protocol내부 함수가 큰 힌트가 됐어요~!

2024-02-05 15:04 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherView.swift
> +    let refreshControl: UIRefreshControl = UIRefreshControl()
캡슐화가 덜 되어있었네요. 수정하겠습니다.

2024-02-05 15:05 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherViewController.swift
> +            weatherForecastInfo: weatherJSON?.weatherForecast[indexPath.row],
safe: 를 쓸 생각은 못했네요. 이부분은 우선 반영하고 따로 학습을 해야 할 거 같아요.
바로 생각이 안나니까 편한대로 썼네요 ㅠㅠ

2024-02-05 15:06 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherViewController.swift
> +    }
위에서 이야기한것처럼 습관적인 optional인거 같아요.
반영해서 수정해 볼게요

2024-02-05 16:02 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDetailViewController.swift
> +        guard let listInfo = weatherDetailInfo?.weatherForecastInfo else { return }
optional을 제거함으로써 굳이 guard문을 쓰지 않아도 되게끔 변경해봤습니다.

2024-02-05 16:40 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +            }
MainActor.run을 이용해서 돌아올 수 있게 처리했습니다.

2024-02-06 15:03 UTC, havilog requested changes
1. Conversation에는 코멘트 확인 
    -> 수정사항이 있을 경우 수정 후 해당 수정 커밋 로그와 함께 어떻게 수정하였는지 코멘트
    -> 수정사항이 없을 경우 지금과 같이 코멘트 or 확인 표시
2. 여러가지 수정사항에 대해 커밋 단위를 쪼개서 각각의 유의미한 수정사항 분리

를 하시면 더욱 커뮤니케이션 하기 좋을 듯 합니다!

커밋은 푸쉬하시고 우클릭 -> 복사 하시면 [0153980](https://github.com/yagom-academy/refactoring-weather/pull/13/commits/01539803af72bce016e00457c925946099540197)
요렇게 표시되어서 수정 커밋과 코멘트를 같이 남겨주시면 커뮤니케이션이 더욱 원활할 거 같아요!

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/NetworkManager.swift
> +struct NetworkManager {
1. 이 아이도 프로토콜로 추상화를 할 수 있지 않을까요?
2. getIconImage 두 함수가 유의미한 단위로 쪼개지지 않은거 같아요

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/ImageCacheManager.swift
> +    }
이 아이들도 ImageCachable 과 같은 프로토콜로 추상화 할 수 있지 않을까요?
DiskCache가 들어갈 수도 있다는 생각이 드네요!

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDataManager.swift
> +        let info: T
이 아이는 29번째 줄에서 선언해도 될 거 같아요!

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDataManager.swift
> +                                        completion: @escaping (Result<T, Error>) -> Void
아래 함수에서는 비동기 처리가 일어나지 않고 있는거 같아요!
completion이 escaping인 이유와,
throwing하는 함수를 Result로 변경하신 이유가 궁금합니다~

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +            let formatter: CustomDateFormatter = .init(timeStyle: .short)
formatter의 경우도 의존성으로 주입받을 수 있지 않을까요?

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +        Task {[weak self] in
Task에서는 반드시 self를 weak로 잡아줘야할까요?
weak로 안잡았을 때 어떻게 동작하시는지 설명해주시면 좋을 듯 합니다~!

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherTableViewCell.swift
> +        }
같은 코드가 반복되고 있는것 같아요.
ImageView에 extension을 만들어보는 것은 어떨까요?

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherView.swift
> +        tableView.register(WeatherTableViewCell.self, forCellReuseIdentifier: "WeatherCell")
reuseIdentifier를 string literal이 아닌 protocol로 관리해보는건 어떨까요?

2024-02-06 15:03 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherViewController.swift
> +              let weatherForecastInfo = weatherJSON?.weatherForecast[indexPath.row]
safe subscript를 만들고 안쓰신거 같아요!

2024-02-06 15:29 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/NetworkManager.swift
> +struct NetworkManager {
1. NetworkManagerDelegate 생성하여 NetworkManager가 추상화 될 수 있도록 했습니다.
`protocol NetworkManagerDelegate { func getIconImage(with urlString: String) async -> UIImage? }`

2. 이부분은 getIconImage(byName:) 함수는 NetworkManager내부에서 제거하고, 외부에서 urlString을 만들어 주입하는 protocol상 정의된 함수만 남길 수 있도록 수정했습니다.

2024-02-06 16:16 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/ImageCacheManager.swift
> +    }
[f11916b](https://github.com/yagom-academy/refactoring-weather/pull/13/commits/f11916bb509b0333caf6c0a651cd2fa3dd834c0f)

1. ImageCacheable을 구현해서 메모리와 디스크에서 각각 캐시이미지를 가져올 수 있게 구현했습니다.
`protocol ImageCacheable {
    func setImage(_ image: UIImage, forKey key: String)
    func getImage(forKey key: String) -> UIImage?
}`

2. 이미지를 메모리 -> 디스크 캐시 순으로 찾을 수 있도록 변경하였고, 거기서도 없으면 다운로드 하도록 순서를 변경해봤습니다.

2024-02-06 16:17 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDataManager.swift
> +        let info: T
넵 수정했습니다.(기본코드라고 그냥 내버려뒀었네요;;)

2024-02-06 16:29 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDataManager.swift
> +                                        completion: @escaping (Result<T, Error>) -> Void
이미지를 붙여서 온다고 생각하다보니 비동기 통신을 생각하면서 코드를 작성했던거 같아요.
그 때문에 습관적으로 @escaping이 붙었네요.
Result로 변경한 이유 역시 습관적으로 JsonDecoder를 쓰는 쪽에서 받는걸 성공과 실패가 있을것이라고 생각하면서 작성했던걸로 기억합니다.

2024-02-06 16:38 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +            let formatter: CustomDateFormatter = .init(timeStyle: .short)
formatter도 의존성을 주입받을 수 있게 수정했습니다.

진행하면서 궁금했던 점이 있습니다.
tableViewCell의 경우 init에서 넣어줄 수 없다보니,  configure에서 많은 의존성주입이 되고있는데 이게 괜찮은지 좀 궁금하네요.. 이런경우 @havilog 는 어떻게 처리하시나요??

2024-02-06 16:43 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +        Task {[weak self] in
해당 로직 내에서 networkManager를 이용하여 아이콘 이미지를 가져오는 부분이 있어, 혹시 순환참조가 걸려 메모리 누수가 생길까 싶어, 안전한 코드 진행을 위해 Task 내에 weak self를 사용했었습니다.

2024-02-06 17:06 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherTableViewCell.swift
> +        }
extension을 쓰니까, 의존성도 분리 되는 느낌이 조금 드네요.
setImage하는 부분은 UIImageView extension으로 이동했습니다 .

2024-02-06 17:13 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherView.swift
> +        tableView.register(WeatherTableViewCell.self, forCellReuseIdentifier: "WeatherCell")
보통 cell 내부에 static let으로 선언해서 사용한 적은 많았는데, 
protocol을 이용하는 부분까진 처음 접해보는 거 같아요.
같은 코드인데 통일성이 생겼다는게 코드를 수정하면서도 참 신기하네요 😆

2024-02-06 17:14 UTC, witlim1225 commented on WeatherForecast/WeatherForecast/WeatherViewController.swift
> +              let weatherForecastInfo = weatherJSON?.weatherForecast[indexPath.row]
한군데만 쓰고 다른데는 못봤네요;;
바로 반영했습니다.

2024-02-07 15:06 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherView.swift
> +        tableView.register(WeatherTableViewCell.self, forCellReuseIdentifier: "WeatherCell")
https://kirkim.github.io/ios/2022/08/11/cellreuseidentifier.html
이런식으로 하면, 모든 셀이 reuseIdentifier를 가질 수 있어요

2024-02-07 15:08 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +        Task {[weak self] in
Task의 경우 내부적으로 implicit하게 self를 잡고있어서 메모리 릭이 발생하지는 않고, delay deallocation이 발생해요.
해당 부분을 참고해서 개발하시면 좋을 듯 합니다~

2024-02-07 15:09 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDetailView.swift
> +            let formatter: CustomDateFormatter = .init(timeStyle: .short)
Dependency Factory를 사용하거나, default값을 넣어주면 좋을 듯 합니다.
또한 imageView의 extension에서,
메모리 캐시, 디스크 캐시, 네트워크 의존성을 넣어주는게 아닌,
ImageLoader와 같은 객체를 만들어서 주입해주고,
ImageLoader에 디펜던시로 위 세개를 가지고 있게 하는 방법도 있을 듯 하네요

2024-02-07 15:10 UTC, havilog commented on WeatherForecast/WeatherForecast/WeatherDataManager.swift
> +                                        completion: @escaping (Result<T, Error>) -> Void
try하는 함수를 굳이 Result로 바꾸는건 시그니처가 헷갈릴 수도 있을거 같아요
throws하는 함수로도 충분할 듯 합니다!

2024-02-07 15:10 UTC, merged