날씨앱 [STEP 1] Lets
yagom-academy/refactoring-weather pull request #17
Opened 2024-02-08 04:28 UTC by alpaka99

안녕하세요 하비 레츠입니다 :)
늦었지만 날씨앱 리팩토링한것을 올리겠습니다.

2024-02-08 10:48 UTC, havilog requested changes
> 어떻게 하면 코드가 이상한? 혹은 고쳐야할점이 눈에 들어올까요?

사실 이 부분은 경험의 영역이라고 생각해요
이렇게 짜면 이게 문제가 되겠구나
저렇게 하면 이게 불편하구나 이거는 경험하지 않으면 알기 어려운것 같습니다

> 너무 많은 책임을 가지는 타입을 여러 타입으로 분리해줍니다.

프로토콜을 조합해 하나의 프로토콜을 만드는 경우도 있지만,
현재 상황에서는 여러 개의 의존성을 가진 하나의 객체를 만들고
해당 객체가 다른 객체들에 의존하도록 하는게 낫지 않을까 싶습니다~!

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Extensions/Date+.swift
> +}
이런 syntax sugar의 경우
편하게 사용할 수는 있지만
테스터빌리티가 줄어들 수 있어요
사용성과 테스트의 트레이드 오프는 생각하시면 좋을 것 같구,
locale이나 timezone등도 파라미터로 받으면 확장성 있을거 같아요

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailView.swift
> +    let spacingView: UIView = UIView()
외부에서 접근하지 않는다면 private을 디폴트로 붙여주세요!

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailView.swift
> +    lazy var mainStackView: UIStackView = .init(arrangedSubviews: [
레이아웃을 하는 시점에 넣어줘도 될거 같아요!
lazy라는 키워드는 사용될 수도 있고 아닐수도 있다는 의미를 담고있어서요
또한 휴먼에러에 의해 variable이라 스택뷰가 바뀔수도 있을거 같아요

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailView.swift
> +    }
1. UIImageView에 Extension으로 이미지를 세팅하는 함수를 만들어보는건 어떨까요?
2. 해당 함수에서 ImageLoader와 같은 객체를 선언해 이미지 로드 여부를 처리하고
3. 해당 객체에서는 캐싱을 담당하는 객체를 통해 디스크 캐시 / 메모리 캐시에 캐시가 있는지 검사해서 있으면 반환
4. 없으면 이미지 로드를 담당하는 객체를 통해 이미지 로드
를 해보면 좋을 거 같아요

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +    private var tempUnit: TempUnit = .celsius
디테일 뷰컨에서는 필요한 정보를 optional이 아닌 값으로 받을 수 있지 않을까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +            weatherForecastInfo: weatherForecastInfo!,
force casting은 존재하지 않는 기능이라고 생각하고 개발해주시면 좋을거 같아요!

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +        weatherDetailView.tempUnit = tempUnit
1. 이 아이들도 weatherForecastInfo와 같이 하나의 information에 담아서 전달할수도 있을거 같아요
2. 이 아이들은 init시점이 아닌 시점에 전달해주는 이유는 뭘까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastModel.swift
> +//    }
안쓰이는 주석의 경우 지워주시면 좋을 것 같아요!

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastModel.swift
> +}
이 객체의 존재의 이유가 잘 이해가 안되는데요,
이 모델을 왜 구현하였고, 어떤 역할을 하는지 설명해주실 수 있으실까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastViewController.swift
> +    private var tableView: UITableView!
이 친구는 왜 나중에 initialize해줄까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastViewController.swift
> +    private let imageCache: ImageCache
이 친구는 왜 프로토콜이 아닌 구체타입에 의존하고 있을까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastViewController.swift
> +    }
함수 이름은 새로운 json을 가져오는 건데, 실제로는 타이틀을 바꿔주고 있네요

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherTableViewCell.swift
> +    static let reuseIdentifier: String = String(describing: WeatherTableViewCell.self)
https://kirkim.github.io/ios/2022/08/11/cellreuseidentifier.html
와 같이 프로토콜을 사용해서 reuseIdentifier를 선언해보는건 어떨까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherTableViewCell.swift
> +    private var descriptionLabel: UILabel!
이 친구들도 스토리보드를 사용하는게 아니라면 layoutViews 시점에 initialize하지 않아도 괜찮을거 같아요

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherTableViewCell.swift
> +        weatherLabel.text = info.weather.main
main이라는 단어는 어떤 값을 의미하는지 파악이 힘드네요

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/NSDataAssetConvertor.swift
> +//}
이파일은 안쓰이는거 같아요

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/ImageCache.swift
> +    typealias Value = UIImage
이 값들을 typealias로 잡아주신 이유가 뭘까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/ImageCache.swift
> +    private var cache: NSCache<NSString, UIImage>
이 아이는 let이어도 될 것 같아요

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +struct DataFetcher: DataFetchable {
이 아이는 json을 가져오는 로직과, 리모트에서 이미지를 가져오는 로직 두가지를 가지고 있는거 같아요
각각 쪼개서 구현하는건 어떨까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +    }
throwing하는 함수 다시 throw시키지 않고, try?로 캐스팅해서 nil로 반환하는 이유가 뭘까요?

2024-02-08 10:48 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +    func fetchImage(hashableURL: any Hashable) async -> UIImage? {
이미지의 URL이 hashable한 이유는 뭔가요?

2024-02-08 12:56 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Extensions/Date+.swift
> +}
아하 그렇군요...!
이 locale과 timezone을 파라미터로 받는 방식은 생각해보지 못 했는데 확인해보도록 하겠습니다 감사합니다!

2024-02-08 13:00 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailView.swift
> +    let spacingView: UIView = UIView()
넵 알겠습니다! 아직 접근제어 부분에서 많이 부족하네요;

2024-02-08 13:02 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailView.swift
> +    lazy var mainStackView: UIStackView = .init(arrangedSubviews: [
그렇다면 let으로 선언한 mainStackView에 subview들을 넣어주는 함수를 따로 만들어서 넣어주는게 나을까요?

2024-02-08 13:02 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailView.swift
> +    }
오... 알겠습니다 한번 말씀하신대로 고쳐보겠습니다!

2024-02-08 13:03 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +    private var tempUnit: TempUnit = .celsius
한번 옵셔널이 아닌 값으로 받아올 수 있게 다시 리팩터링 해보도록 하겠습니다!

2024-02-08 13:03 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +            weatherForecastInfo: weatherForecastInfo!,
앗 넵 저런 부분에서 오류가 발생하면 앱이 터지겠군요..!
다른 방법으로 리팩터링 해보도록 하겠습니다

2024-02-08 13:10 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +        weatherDetailView.tempUnit = tempUnit
1. 음 넵 하나의 구조체에 담아서 전달하라는 말씀이시군요...!
2. 아 자세히 보니 이 코드는 쓸모없는 코드였네요;; self의 변수값들을 다시 스스로 할당하고 있었군요...!

2024-02-08 13:17 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastModel.swift
> +}
음 아마 원래는 현재 DataFetcher의 역할을 이 클래스에서 일부 했던것 같습니다. 그런데 제가 데이터를 가져오는 역할들을 한번에 DataFetcher 구조체로 묶어서 이전시키면서 이 클래스의 존재의의가 사라진것 같습니다. 현재는 도시와 도시이름, 날씨 상태등을 담고 있긴 한데 그렇다면 decoder와 weatherJSON등의 변수로 선언된 부분들을 고쳐야겠습니다. 이 부분은 고쳐서 다시 PR올리도록 하겠습니다.
알려주셔서 감사합니다!

2024-02-08 13:17 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastModel.swift
> +//    }
아 넵 뭔가 제 생각을 주저리주저리 적어놨는데 지우는걸 깜빡했습니다.
지우고 다시 PR 올리도록 하겠습니다..!

2024-02-08 13:27 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastViewController.swift
> +    private var tableView: UITableView!
음... 아마 layoutTable이라는 메서드에서 따로 init과 동시에 레이아웃을 잡는 과정을 진행하기 위해서인것 같습니다...!
저도 보통은 이런식으로 내부 뷰들은 추후에 initialize하는 방식을 사용하는데 혹시 어떤 문제점이 있을까요?

2024-02-08 13:28 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastViewController.swift
> +    private let imageCache: ImageCache
아 이 부분을 제가 프로토콜로 바꿔서 의존성을 주입시켜주는것을 까먹고 있었네요!
수정해서 PR 올리도록 하겠습니다.
감사합니다!

2024-02-08 13:29 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastViewController.swift
> +    }
앗 이 부분의 메서드 이름을 바꿔줘야겠군요.
알려주셔서 감사합니다 하비!

2024-02-08 13:42 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherTableViewCell.swift
> +    static let reuseIdentifier: String = String(describing: WeatherTableViewCell.self)
아 저도 항상 String 값을 하드코딩해서 넣었는데 하비가 올려주신 포스트 잘 참고해보겠습니다!
감사합니다 :)

2024-02-08 13:43 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherTableViewCell.swift
> +        weatherLabel.text = info.weather.main
아 가독성이 떨어지는군요...!
확실히 main이라고만 한다면 미래의 저 혹은 다른 동료가 봤을때는 어떤 코드인지 파악이 힘들겠네요.
수정해서 PR 올리도록 하겠습니다 감사합니다!

2024-02-08 13:50 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +struct DataFetcher: DataFetchable {
아 넵 제가 궁금했던 부분도 이 부분이었습니다.
뭔가 protocol을 만드는 기준을 역할로 나눴을때는 '데이터를 가져오는 프로토콜'이라는 하나의 프로토콜로 묶어서 만드는 판단을 했었습니다.
음... 그렇게 하는게 아니라 최상위에 Fetchable 프로토콜을 두고 WeatherJSONFetchable, ImageFetchable, NSDataAssetFetchable 프로토콜을 따로 만드는게 로직을 분리하는 부분에서 맞는 방향이었을까요? 궁금합니다!

2024-02-08 13:57 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +    }
음... 아마 이 부분은 앞에서 코드를 짠 부분이 WeatherInfo를 옵셔널로 받아서 이렇게 만들어둔것 같습니다.
제가 throw하는 함수를 많이 다뤄보지 않아서 그런데 보통은 throw하는 함수가 안에 있다면 다시 throw를 해서 최종적으로 값을 받는곳에서 에러 핸들링을 하는걸까요...?

2024-02-08 13:58 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Utils/ImageCache.swift
> +    private var cache: NSCache<NSString, UIImage>
앗 알겠습니다. 수정해서 PR 다시 올리도록 하겠습니다..!

2024-02-08 13:59 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Utils/ImageCache.swift
> +    typealias Value = UIImage
아마 아래에 subscript 부분에서 Key와 Value로 찾는 느낌을 위해서 이런식으로 typealias를 해둔것 같습니다...!

2024-02-08 13:59 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Utils/NSDataAssetConvertor.swift
> +//}
아 이 부분도 DataFetcher를 만들면서 deprecated된 부분이네요. 수정해서 PR 올리도록 하겠습니다.
알려주셔서 감사합니다..!

2024-02-08 16:00 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailView.swift
> +    lazy var mainStackView: UIStackView = .init(arrangedSubviews: [
아 이제보니 lazy로 선언한 이유가 let으로 선언하면 init하는 시점에 stackView 내부의 값들이 init 되어있지 않을 수 있어서 이런식으로 lazy를 이용해서 선언하는것 같습니다.
스택뷰는 let으로 선언해놓고, 하단에 layoutStackView 메서드를 새로 생성해서 초기 레이아웃을 잡을때 넣어주는 방식으로 수정하였습니다!

2024-02-09 01:43 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailView.swift
> +    let spacingView: UIView = UIView()
수정해서 PR에 반영해놨습니다!

2024-02-09 01:43 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +    private var tempUnit: TempUnit = .celsius
수정해서 PR에 commit 해놓았습니다!

2024-02-09 01:43 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +            weatherForecastInfo: weatherForecastInfo!,
수정해서 PR 해놓았습니다!

2024-02-09 01:43 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherDetail/WeatherDetailViewController.swift
> +        weatherDetailView.tempUnit = tempUnit
수정해서 PR에 올려놨습니다!

2024-02-09 01:44 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastModel.swift
> +//    }
수정해서 PR에 반영해놓았습니다!

2024-02-09 02:11 UTC, alpaka99 commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +    func fetchImage(hashableURL: any Hashable) async -> UIImage? {
이전 코드들에서 fetchImage를 두가지 방법으로 하고 있었습니다. 한가지는 URL을 통한 방식이었고 한가지는 String을 통한 방식이었습니다. 그래서 두가지 전부 채택 가능한 Hashable을 사용해서 함수를 만들었습니다...!

2024-02-09 04:52 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastViewController.swift
> +    private var tableView: UITableView!
일단 이 방법은 매우 위험해요.
storyboard와 연결해서 사용할 경우 어쩔 수 없지만,
휴먼에러에 의해 테이블 뷰를 초기화해주지 않는 경우 앱이 크래시날 수 있고 이 부분은 매우 치명적이에요
따라서 초기화는 init시점에 해주고, 테이블 내부에 대한 설정을 viewDidLoad시점으로 옮기는게 좋아보여요

2024-02-09 04:53 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/ImageCache.swift
> +    typealias Value = UIImage
아.. 이 부분도 직접 구현하신게 아니군요 ..! 사실 이 alias는 오히려 코드 복잡도를 높이는 느낌이라 지양하는게 좋을거 같다는 느낌이 들었어요

2024-02-09 04:59 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +    func fetchImage(hashableURL: any Hashable) async -> UIImage? {
any로 들어가게 되면 다른 hashable하지만, 유효하지 않은 값이 들어갈 수도 있을거 같아요!
제네릭으로 제약을 걸어서 넣어주거나, 인터페이스 두 개를 만들고 하나의 공통로직을 실행하게 할 수도 있을거 같아요

2024-02-09 05:00 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +    }
do - try를 하고 싶지 않다! 라고 한다면 이렇게 처리해도 틀린 것은 아니지만,
함수에서 나온 에러를 그대로 외부로 던져주고
외부에서 에러를 핸들링하는 방식을 저는 더 애용하고 있습니다 ㅎㅎ

2024-02-09 05:03 UTC, havilog commented on WeatherForecast/WeatherForecast/Utils/DataFetcher.swift
> +struct DataFetcher: DataFetchable {
사실 제 생각에는 위 3개의 프로토콜이 그렇게 연관성이 높아보이지는 않는거 같아요 ㅎㅎ
Fetch를 하는 기능이 비슷하기는 하지만,
프로토콜을 합성하고, 분리하기 보다는 각각의 프로토콜을 선언하고 / 구현한 객체들을 잘 합성하는게 좋을 것 같아요.

2024-02-09 05:04 UTC, havilog commented on WeatherForecast/WeatherForecast/Scenes/WeatherForecast/WeatherForecastModel.swift
> +}
넵 일반적으로는 네트워크(현재는 JSON)을 가져오는 객체에서 디코딩을 해주고 있어서 그 부분에서 
디코딩을 해서, 원하는 모델로 반환해주면 될 거 같아요!

2025-01-13 12:02 UTC, closed without merging