날씨앱 [STEP 1] Choiy
yagom-academy/refactoring-weather pull request #9
Opened 2024-02-02 19:22 UTC by ChoiysApple

@KYHyeon
안녕하세요! 이번에도 잘부탁드립니다!

## 고민했던 점
- `ViewController`의 네이밍이 어떤 뷰인지 알아차리기 힘들다고 생각해 이를 `WeatherListViewController`로 바꿔주었습니다.
- 전반적으로 `ViewController`에 `View` 설정을 하는 코드가 너무 많아 이를 분리하고자 하였습니다. View 관련 부분을 새로운 `UIView`로 분리하고 delegate를 통해 `View`와 `ViewController`가 상호작용 하도록 수정하였습니다.
- 날씨 데이터를 불러오는 로직을 별도의 클래스로 분리하였습니다. 해당 클래스가 바뀌어도 변경이 최소화 될 수 있도록 `WeatherAPI`라는 이름의 프로토콜을 만들어 추상화 해보았습니다.

--

## 해결하지 못한 부분
### `ViewController`가 `View`의 프로퍼티들을 직접 접근하지 못하기 때문에 발생하는 문제
- 기존 코드의 `tableview(cellForRowAt:)`코드 내부에서는 Cell에 비동기적으로 받아온 이미지를 삽입하기 전에 올바른 Cell에 삽입되는 건지를 indexPath를 이용해 체크하는 로직이 있는데, 뷰와 뷰컨이 분리되면서 뷰컨에서 `tableView`에 접근할 수 없어 `tableView.indexPath(for cell:)`메서드 사용할 수 없어 해당 로직 구현에 실패했습니다.
```swift
// 기존 CellForRowAt 메서드 내부
Task {
    guard let url: URL = URL(string: urlString),
          let (data, _) = try? await URLSession.shared.data(from: url),
          let image: UIImage = UIImage(data: data) else {
        return
    }
    
    imageChache.setObject(image, forKey: urlString as NSString)
    
    if indexPath == tableView.indexPath(for: cell) {
        cell.weatherIcon.image = image
    }
}

// 변경된 CellForRowAt 메서드 내부 (setImage 메서드 내부에서 indexPath 비교 로직이 없습니다.)
let iconName: String = weatherForecastInfo.weather.icon
weatherAPI.fetchImage(iconName: iconName) { image in
    cell.setImage(image: image)
}

- 
```
---

## 조언을 얻고 싶은 부분
### Navigation 관련 동작 설정을 `ViewController`가 아닌 `View`에서 하는 것이 좋은 방법일까?
- 현재 `View`관련 delegate에 `navigationBarItem`을 추가해서 뷰에 데이터가 들어올 때 네비게이션 버튼이나 타이틀도 `View`에서 같이 초기화 해주고 있습니다.
- 뷰와 관련된 부분의 초기화 코드를 모두 `View`가 결정한다고 생각해 이런 식으로 구현하였는데, `ViewController`가 가지고 있는 프로퍼티를 protocol을 이용해 다른 부분에서 초기화 하는 것이 오히려 어색하거나 비효율적일 수도 있다는 생각이 들어 조언을 구하고 싶습니다.
```swift
// 날씨 상세 화면의 예시입니다
protocol WeatherDetailDelegate {
    var navigationItem: UINavigationItem { get }
}

class WeatherDeatilView: UIView {
    ...
   private func setUpData(weatherForecastInfo: WeatherForecastInfo?, tempExpression: String) {
        
        // 다른 UI 프로퍼티 설정

        // 네비게이션 설정
        if let timeInterval = weatherForecastInfo?.dt {
            let date = Date(timeIntervalSince1970: timeInterval)
            delegate.navigationItem.title = dateFormatter.string(from: date)
        }
    }
    ...
}
```

### Delegate를 두개를 사용하여 `View`에서도 `ViewController`의 delegate를 채택하는 방법
- 위에서 언급한 **해결하지 못한 부분**은 `View`뿐만 아니라 `ViewController`에서도 delegate를 가지고 이 delegate를 통해 `ViewController`에서도 `View`의 delegate 메서드를 실행시키는 방식으로 해결이 가능할 것 같습니다.
- 그런데 이방법은 `View`와 `ViewController`간의 결합도를 높이는 방법인 것 같다는 생각이 들지만, 한편으로는 만약 `View`나 `ViewController`가 바뀌었을 때 delegate들만 맞추어 주면 되니 큰 문제가 없는 방법인가? 라는 생각도 들어서 이 방법에 문제가 없을지 알고 싶습니다!

2024-02-03 10:13 UTC, KYHyeon requested changes
안녕하세요! 이번 주 step1도 고생 많으셨습니다.
ISP와 DIP를 잘 구현하셨네요 다만 SRP 관점에서 우려되는 부분이 보여 댓글을 남겼습니다.
확인해보시고 한번 더 개선을 검토 해보면 좋을 것 같아요

> 해결하지 못한 부분
> ViewController가 View의 프로퍼티들을 직접 접근하지 못하기 때문에 발생하는 문제
> 기존 코드의 tableview(cellForRowAt:)코드 내부에서는 Cell에 비동기적으로 받아온 이미지를 삽입하기 전에 올바른 Cell에 삽입되는 건지를 indexPath를 이용해 체크하는 로직이 있는데, 뷰와 뷰컨이 분리되면서 뷰컨에서 tableView에 접근할 수 없어 tableView.indexPath(for cell:)메서드 사용할 수 없어 해당 로직 구현에 실패했습니다.
> // 기존 CellForRowAt 메서드 내부
> Task {
>     guard let url: URL = URL(string: urlString),
>           let (data, _) = try? await URLSession.shared.data(from: url),
>           let image: UIImage = UIImage(data: data) else {
>         return
>     }
>     
>     imageChache.setObject(image, forKey: urlString as NSString)
>     
>     if indexPath == tableView.indexPath(for: cell) {
>         cell.weatherIcon.image = image
>     }
> }
> 
> // 변경된 CellForRowAt 메서드 내부 (setImage 메서드 내부에서 indexPath 비교 로직이 없습니다.)
> let iconName: String = weatherForecastInfo.weather.icon
> weatherAPI.fetchImage(iconName: iconName) { image in
>     cell.setImage(image: image)
> }
> 

ViewController와 View는 분리해서 설계하는 것이 좋을 것 같아요. 다시말해 말씀하신 로직들이 간접적으로 뷰 안에서 수행되고 뷰컨트롤러는 동작을 모르는 것이 좋을 것 같은데요.
tableViewCell이 재사용 되기 때문에 혹시 이미지가 잘못 표시될까 걱정하시는 걸로 이해를 했어요.
셀이 재사용될 때 불리는 [prepareForReuse()](https://developer.apple.com/documentation/uikit/uitableviewcell/1623223-prepareforreuse)를 활용해 보는건 어떨까요? 여기에서 네트워크 요청을 취소할 수 있을 것 같아요

> - 
> 조언을 얻고 싶은 부분
> Navigation 관련 동작 설정을 ViewController가 아닌 View에서 하는 것이 좋은 방법일까?
> 현재 View관련 delegate에 navigationBarItem을 추가해서 뷰에 데이터가 들어올 때 네비게이션 버튼이나 타이틀도 View에서 같이 초기화 해주고 있습니다.
> 뷰와 관련된 부분의 초기화 코드를 모두 View가 결정한다고 생각해 이런 식으로 구현하였는데, ViewController가 가지고 있는 프로퍼티를 protocol을 이용해 다른 부분에서 초기화 하는 것이 오히려 어색하거나 비효율적일 수도 있다는 생각이 들어 조언을 구하고 싶습니다.
> // 날씨 상세 화면의 예시입니다
> protocol WeatherDetailDelegate {
>     var navigationItem: UINavigationItem { get }
> }
> 
> class WeatherDeatilView: UIView {
>     ...
>    private func setUpData(weatherForecastInfo: WeatherForecastInfo?, tempExpression: String) {
>         
>         // 다른 UI 프로퍼티 설정
> 
>         // 네비게이션 설정
>         if let timeInterval = weatherForecastInfo?.dt {
>             let date = Date(timeIntervalSince1970: timeInterval)
>             delegate.navigationItem.title = dateFormatter.string(from: date)
>         }
>     }
>     ...
> }
> Delegate를 두개를 사용하여 View에서도 ViewController의 delegate를 채택하는 방법
> 위에서 언급한 해결하지 못한 부분은 View뿐만 아니라 ViewController에서도 delegate를 가지고 이 delegate를 통해 ViewController에서도 View의 delegate 메서드를 실행시키는 방식으로 해결이 가능할 것 같습니다.
> 그런데 이방법은 View와 ViewController간의 결합도를 높이는 방법인 것 같다는 생각이 들지만, 한편으로는 만약 View나 ViewController가 바뀌었을 때 delegate들만 맞추어 주면 되니 큰 문제가 없는 방법인가? 라는 생각도 들어서 이 방법에 문제가 없을지 알고 싶습니다!

WeatherDetailDelegate이 불렸을 때 네비게이션이 변경되어야 해서 navigationItem을 가지고 있는 것 같은데요
뷰를 조금 더 재사용하기 쉽게 만들고 의존성을 높이려면 뷰에서는 `dateDidChanged(text:)` 와 같은 메시지를 뷰컨트롤러에게 전달하고 뷰컨트롤러에서 네비게이션 타이틀을 변경하도록 바꿔보는건 어떨까요?

2024-02-03 10:13 UTC, KYHyeon commented on WeatherForecast/WeatherForecast/WeatherDetail/WeatherDetailView.swift
> +    private var delegate: WeatherDetailDelegate
delegate를 채택하고 있는 클래스가 WeatherDetailViewController 이기 때문에 서로 강한 참조를 가지게 될 것 같아요

일반적으로는 아래와 같이 사용합니다.
```
protocol WeatherDetailDelegate: **AnyObject**
```

```suggestion
    private weak var delegate: WeatherDetailDelegate?
```

2024-02-03 10:13 UTC, KYHyeon commented on WeatherForecast/WeatherForecast/WeatherList/WeatherListViewController.swift
> +    var weatherAPI: WeatherAPI = OpenWeatherAPI()
프로퍼티를 사용한 DIP를 잘 적용하셨네요! 👍

2024-02-03 10:13 UTC, KYHyeon commented on WeatherForecast/WeatherForecast/Model/OpenWeatherAPI.swift
> +        }
이미지를 네트워크를 통해 다운받아 캐시를 하는 로직을 잘 구현하셨네요
하지만 이 로직은 OpenWeatherAPI가 아니어도 많이 재활용할 수 있을 것 같아요. 별도 객체로 분리해보는건 어떨까요?

2024-02-03 10:13 UTC, KYHyeon commented on WeatherForecast/WeatherForecast/WeatherList/WeatherListViewController.swift
> +class WeatherListViewController: UIViewController {
지금 뷰컨트롤러는 UI로직, 데이터 로딩, 네비게이션 관리 등 여러가지 책임을 갖고 있는데요
SRP 원칙에 따라서 더 작은 단위로 분리해서 뷰컨트롤러의 복잡성을 줄일 수 있을 것 같아요
예를들어 데이터 로딩 로직을 별도의 데이터 관리 객체로 분리하거나, 네비게이션 로직을 라우터 패턴을 사용해서 분리해볼 수 있을 것 같아요

2024-02-03 10:13 UTC, KYHyeon commented on WeatherForecast/WeatherForecast/WeatherList/WeatherListView.swift
> +protocol WeatherListViewDelegate: UITableViewDelegate, UITableViewDataSource {
delegate를 사용해서 WeatherListView에 필요한 인터페이스만 분리해 ISP를 잘 따르셨네요!

2024-02-07 15:47 UTC, ChoiysApple commented
안녕하세요! 피드백 주셨던 부분들 수정해서 다시 리뷰 요청드려요 😀
다만 아직 확실하게 해결이 힘들었거나 구체적인 그림이 잘 그려지지 않는 부분이 있어 조언을 구하고 싶어요

### 1. Protocol이 navigationItem를 가지고 있는 부분
이 부분에 대해서 `dateDidChanged(text:)`과 같은 방법을 제시해주셔서 `WeatherDetailProtocol` 부분의 고민은 해결되었습니다. 하지만 `WeatherListProtocol`에서도 동일하게 `navigationItem`을 가지고 있는 문제가 있는데, 이전과는 다르게 `navigation`의 버튼 입력에 따라 View의 내용도 업데이트가 되어야 되기 때문에 `dateDidChanged(text:)` 같은 방식으로 해결이 곤란하더라구요... 이런 경우에는 ViewController가 View의 데이터를 수정하거나 메서드를 실행시킬 수 있어야 할 것 같은데, 어떤 방식으로 해결하면 좋을지 잘 모르겠습니다 ㅠㅠ

### 2. 데이터 로딩 로직을 별도의 데이터 관리 객체로 분리
`WeatherListViewController`의 데이터를 객체로 분리하는 방향을 말씀해 주셨는데 이미 `weatherAPI` 객체로 분리되어 있다고 생각하고 있어서, 어느 부분을 더 분리하면 좋을지 잘 감이 오지 않아서 힌트를 주시면 감사할 것 같아요 🥹

2024-02-09 05:21 UTC, KYHyeon commented
> @KYHyeon 안녕하세요! 피드백 주셨던 부분들 수정해서 다시 리뷰 요청드려요 😀 다만 아직 확실하게 해결이 힘들었거나 구체적인 그림이 잘 그려지지 않는 부분이 있어 조언을 구하고 싶어요
> 
> ### 1. Protocol이 navigationItem를 가지고 있는 부분
> 이 부분에 대해서 `dateDidChanged(text:)`과 같은 방법을 제시해주셔서 `WeatherDetailProtocol` 부분의 고민은 해결되었습니다. 하지만 `WeatherListProtocol`에서도 동일하게 `navigationItem`을 가지고 있는 문제가 있는데, 이전과는 다르게 `navigation`의 버튼 입력에 따라 View의 내용도 업데이트가 되어야 되기 때문에 `dateDidChanged(text:)` 같은 방식으로 해결이 곤란하더라구요... 이런 경우에는 ViewController가 View의 데이터를 수정하거나 메서드를 실행시킬 수 있어야 할 것 같은데, 어떤 방식으로 해결하면 좋을지 잘 모르겠습니다 ㅠㅠ
> 
말씀하신 것 처럼 ViewController가 View를 알고 있으니 view 프로퍼티를 직접 사용해서 수정하거나 메서드를 실행시킬 수 있을 것 같아요!
- 상위 객체 -> 하위 객체: 메서드나 프로퍼티 직접 실행
- 하위 객체 -> 상위 객체: delegate
이런 나름대로의 규칙을 갖고 데이터를 주고받는다면 일관성있게 만들 수 있지 않을까요
물론 하나의 예시일 뿐이고 input과 output이 구분된다면 다른 방법을 사용해도 좋을 것 같아요

> ### 2. 데이터 로딩 로직을 별도의 데이터 관리 객체로 분리
> `WeatherListViewController`의 데이터를 객체로 분리하는 방향을 말씀해 주셨는데 이미 `weatherAPI` 객체로 분리되어 있다고 생각하고 있어서, 어느 부분을 더 분리하면 좋을지 잘 감이 오지 않아서 힌트를 주시면 감사할 것 같아요 🥹
아..! 그러네요 ㅎㅎ 제가 코드를 착각한 부분이 있었던 것 같습니다
네비게이션 같은 경우는 WeatherListViewController에서 DetailViewController로 넘어가기 위해 뷰컨트롤러가 직접 가지고 있는데 이걸 주입받으면 어떨까 했었어요. 역시 DIP를 적용한다면 더 유연한 코드를 만들 수 있겠지만 취향에 따라 그렇지 않은 것이 유지보수 하는 관점에서 나은 경우도 많아서요. 이대로도 괜찮은 것 같아요

고생 많으셨습니다!

2024-02-09 05:21 UTC, KYHyeon approved these changes

2024-02-09 05:21 UTC, merged